server:
  # 服务器端口
  port: 8001
  servlet:
    # 应用访问路径
    context-path: /
  tomcat:
    # tomcat编码
    uri-encoding: UTF-8
    connection-timeout: 60000

# 日志配置
logging:
  level:
    org.springframework: info
    com.chmorn: debug
  file:
    name: logs/IptvTool.log
    max-size: 100MB

spring:
  application:
    name: IptvTool


